# IMPORTING LIBRARIES

In [65]:
import pandas as pd
import numpy as np
import imblearn
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFE
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn import linear_model
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import PCA
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, accuracy_score, classification_report, confusion_matrix

# READING CSV FILE

In [66]:
df = pd.read_csv("./creditcard.csv")
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...         V21       V22       V23       V24  \
0  0.098698  0.363787  ...   -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425  ...   -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  ...    0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024  ...   -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  ...   -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Amount  Class  
0  0.128539 -0.189115  0.133558 -0.021053  149.62      0  
1  0.167170  0.125895 -0.008983  0.014724    2.69      0  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0  
3  0.647376 -0.221929  0.062723  0.061458  123.50      0  
4 -0.206010  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

# UNDERSAMPLING THE DATA

In [67]:
no_frauds = len(df[df['Class'] == 1])
non_fraud_indices = df[df.Class == 0].index
non_fraud_indices = df[df.Class == 0].index
random_indices = np.random.choice(non_fraud_indices, no_frauds, replace=False)
fraud_indices = df[df.Class == 1].index
under_sample_indices = np.concatenate([fraud_indices,random_indices])
under_sample = df.loc[under_sample_indices]

# UNDERSAMPLED DATAFRAME

In [68]:
under_sample

Time        V1        V2         V3        V4        V5        V6  \
541        406.0 -2.312227  1.951992  -1.609851  3.997906 -0.522188 -1.426545   
623        472.0 -3.043541 -3.157307   1.088463  2.288644  1.359805 -1.064823   
4920      4462.0 -2.303350  1.759247  -0.359745  2.330243 -0.821628 -0.075788   
6108      6986.0 -4.397974  1.358367  -2.592844  2.679787 -1.128131 -1.706536   
6329      7519.0  1.234235  3.019740  -4.304597  4.732795  3.624201 -1.357746   
6331      7526.0  0.008430  4.137837  -6.240697  6.675732  0.768307 -3.353060   
6334      7535.0  0.026779  4.132464  -6.560600  6.348557  1.329666 -2.513479   
6336      7543.0  0.329594  3.712889  -5.775935  6.078266  1.667359 -2.420168   
6338      7551.0  0.316459  3.809076  -5.615159  6.047445  1.554026 -2.651353   
6427      7610.0  0.725646  2.300894  -5.329976  4.007683 -1.730411 -1.732193   
6446      7672.0  0.702710  2.426433  -5.234513  4.416661 -2.170806 -2.667554   
6472      7740.0  1.023874  2.001485  -4.769752  3.819195 -1.271754 -1.734662   
6529      7891.0 -1.585505  3.261585  -4.137422  2.357096 -1.405043 -1.879437   
6609      8090.0 -1.783229  3.402794  -3.822742  2.625368 -1.976415 -2.731689   
6641      8169.0  0.857321  4.093912  -7.423894  7.380245  0.973366 -2.730762   
6717      8408.0 -1.813280  4.917851  -5.926130  5.701500  1.204393 -3.035138   
6719      8415.0 -0.251471  4.313523  -6.891438  6.796797  0.616297 -2.966327   
6734      8451.0  0.314597  2.660670  -5.920037  4.522500 -2.315027 -2.278352   
6774      8528.0  0.447396  2.481954  -5.660814  4.455923 -2.443780 -2.185040   
6820      8614.0 -2.169929  3.639654  -4.508498  2.730668 -2.122693 -2.341017   
6870      8757.0 -1.863756  3.442644  -4.468260  2.805336 -2.118412 -2.332285   
6882      8808.0 -4.617217  1.695694  -3.114372  4.328199 -1.873257 -0.989908   
6899      8878.0 -2.661802  5.856393  -7.653616  6.379742 -0.060712 -3.131550   
6903      8886.0 -2.535852  5.793644  -7.618463  6.395830 -0.065210 -3.136372   
6971      9064.0 -3.499108  0.258555  -4.489558  4.853894 -6.974522  3.628382   
8296     11080.0 -2.125490  5.973556 -11.034727  9.007147 -1.689451 -2.854415   
8312     11092.0  0.378275  3.914797  -5.726872  6.094141  1.698875 -2.807314   
8335     11131.0 -1.426623  4.141986  -9.804103  6.666273 -4.749527 -2.073129   
8615     11629.0 -3.891192  7.098916 -11.426467  8.607557 -2.065706 -2.985288   
8617     11635.0  0.919137  4.199633  -7.535607  7.426940  1.118215 -2.886722   
...          ...       ...       ...        ...       ...       ...       ...   
50889    44694.0 -0.620122  0.617055   1.250467  1.178431  0.327072  0.513977   
193280  130070.0  2.045981 -0.164239  -1.222500  0.216033  0.039429 -0.683001   
283652  171763.0  2.053050 -0.062240  -1.067222  0.409487 -0.115800 -1.129875   
105624   69618.0  1.197126  0.317572   0.501172  1.253901 -0.592741 -1.286073   
57861    48111.0  1.316973 -1.663936   1.662803 -0.730897 -2.425891  0.461002   
29973    35722.0  1.249660 -1.058342   0.309025 -2.108688 -1.029756  0.132932   
243813  152083.0  1.705094 -0.531436  -0.841908  1.737357 -0.289022 -0.330495   
55512    46979.0 -1.184004 -0.245092  -0.110711 -1.632928 -1.117302 -0.335370   
94564    64942.0  0.679873  0.486313   0.984962  1.468136 -0.716051 -0.250064   
137813   82340.0  1.190041  0.077708   0.624772  0.952175 -0.496203 -0.222187   
259086  158948.0  2.165926  0.132929  -2.447897 -0.297116  1.058266 -0.908325   
179917  124289.0  0.090221 -3.500671  -2.782185  0.668377  0.077821  1.796609   
272021  164871.0 -0.662734  1.188128  -1.056263 -1.165559 -0.834989  0.530834   
109559   71436.0  0.839640 -0.917731   1.175804  1.538371 -0.901176  1.544846   
90636    63097.0  0.959554 -0.526662   1.166454  0.721256 -1.254632 -0.177612   
203635  134898.0 -1.177089  1.090273   1.722230  2.522684 -1.030275  0.516655   
81686    59046.0  0.008415  0.524899  -0.121898 -0.457915  1.334172 -0.595869   
139529   83194.0 -1.240796  1.322041   0.06

# SPLITTING THE DATASET INTO TRAIN AND TEST

In [69]:
X_under = under_sample[['V1','V2','V3','V4','V5','V6','V7','V8','V9','V10','V11','V12','V13','V14','V15','V16','V17','V18','V19',
                        'V20','V21','V22','V23','V24','V25','V26','V27','V28','Amount']]
y_under = under_sample['Class']
X_under_train, X_under_test, y_under_train, y_under_test = train_test_split(X_under,y_under,test_size = 0.3, random_state = 0)

# RFE ON LOGISTIC REGRESSION

In [70]:
model = LogisticRegression()
rfe = RFE(model)
fit = rfe.fit(X_under_train,y_under_train)
print("Number of Features: %d"% fit.n_features_)
print("Selected features: %s"% fit.support_)
print("Ranking of features: %s"% fit.ranking_)  

Number of Features: 14
Selected features: [False False  True  True False False  True  True False  True False  True
  True  True False  True False False  True False False False  True False
  True  True  True False False]
Ranking of features: [10  2  1  1  4 14  1  1 11  1  5  1  1  1 16  1  6  3  1  9 13  7  1  8
  1  1  1 12 15]


# MODEL FITTING ON TRAIN DATA

In [71]:
logreg = LogisticRegression()
## fitiing the model
X = X_under_train[['V1','V2','V4','V7','V8','V10','V11','V12','V14','V20','V22','V23','V24','V27','V28']]
logreg.fit(X, y_under_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [72]:
prediction = logreg.predict(X)
print(confusion_matrix(y_under_train,prediction))  
print(classification_report(y_under_train,prediction))
print(accuracy_score(y_under_train, prediction))

[[332  11]
 [ 32 313]]
             precision    recall  f1-score   support

          0       0.91      0.97      0.94       343
          1       0.97      0.91      0.94       345

avg / total       0.94      0.94      0.94       688

0.9375


# MODEL FITTING ON TEST DATA

In [73]:
# fitting the model
X2 = X_under_test[['V1','V2','V4','V7','V8','V10','V11','V12','V14','V20','V22','V23','V24','V27','V28']]

In [74]:
prediction2 = logreg.predict(X2)
print(confusion_matrix(y_under_test,prediction2))  
print(classification_report(y_under_test,prediction2))
print(accuracy_score(y_under_test, prediction2))

[[145   4]
 [ 13 134]]
             precision    recall  f1-score   support

          0       0.92      0.97      0.94       149
          1       0.97      0.91      0.94       147

avg / total       0.94      0.94      0.94       296

0.9425675675675675


# GRID SEARCH ON TRAIN DATA

In [75]:
# Logistic regression
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler

logregpipe = Pipeline([('scale', StandardScaler()),
                   ('logreg',LogisticRegression(multi_class="multinomial",solver="lbfgs"))])

# Gridsearch to determine the value of C
param_grid = {'logreg__C':np.arange(0.01,100,10)}
logreg_cv = GridSearchCV(logregpipe,param_grid,cv=5,return_train_score=True)
logreg_cv.fit(X,y_under_train)
print(logreg_cv.best_params_)

bestlogreg = logreg_cv.best_estimator_
bestlogreg.fit(X,y_under_train)
bestlogreg.coef_ = bestlogreg.named_steps['logreg'].coef_
bestlogreg.score(X,y_under_train)

{'logreg__C': 90.01}


0.938953488372093

# GRID SEARCH ON TEST DATA

In [76]:
bestlogreg = logreg_cv.best_estimator_
bestlogreg.fit(X2,y_under_test)
bestlogreg.coef_ = bestlogreg.named_steps['logreg'].coef_
bestlogreg.score(X2,y_under_test)

0.9662162162162162

# CROSS VALIDATION ON TRAIN DATA

In [77]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn import cross_validation

predicted = cross_validation.cross_val_predict(LogisticRegression(),X,y_under_train,cv=10)
print (metrics.accuracy_score(y_under_train, predicted))

0.9316860465116279


# CROSS VALIDATION ON TEST DATA

In [78]:
predicted1 = cross_validation.cross_val_predict(LogisticRegression(),X2, y_under_test, cv=10)

print (metrics.classification_report(y_under_test, predicted1))
print (metrics.accuracy_score(y_under_test, predicted1))

             precision    recall  f1-score   support

          0       0.93      0.94      0.94       149
          1       0.94      0.93      0.94       147

avg / total       0.94      0.94      0.94       296

0.9358108108108109


# K BEST ON LOGISTIC REGRESSION

In [79]:
array = under_sample.values
test = SelectKBest(score_func=f_classif, k=10)
fit = test.fit(X_under_train, y_under_train)
print("scores_:",test.scores_)
print("pvalues_:",test.pvalues_)
print("selected index:",test.get_support(True))
print("after transform:",test.transform(X_under_train)) 

scores_: [1.67089699e+02 2.31150010e+02 3.43777098e+02 6.82717697e+02
 1.08703487e+02 1.35804896e+02 2.33786902e+02 5.33029739e+00
 3.04457984e+02 4.83731182e+02 6.00494806e+02 6.62258650e+02
 3.33263300e-01 8.93769615e+02 9.92065190e-01 3.87211996e+02
 3.14237774e+02 1.98662673e+02 6.20974417e+01 1.64463003e+01
 1.99969213e+01 6.58982729e-01 1.78740225e+00 4.18800021e+00
 9.37210177e-02 1.26307481e-01 1.13535257e+01 3.62524257e+00
 2.60587241e+00]
pvalues_: [2.30716364e-034 3.33551015e-045 1.61750764e-062 5.46429413e-105
 1.00119843e-023 9.22387429e-029 1.24072394e-045 2.12541779e-002
 1.06112671e-056 1.51398196e-081 9.56237860e-096 9.64494821e-103
 5.63933233e-001 2.23014881e-126 3.19589342e-001 1.09122855e-068
 3.60936901e-058 8.32179086e-040 1.28489384e-014 5.57905660e-005
 9.07588171e-006 4.17200889e-001 1.81686169e-001 4.10917380e-002
 7.59591786e-001 7.22400966e-001 7.95199526e-004 5.73274103e-002
 1.06928395e-001]
selected index: [ 2  3  6  8  9 10 11 13 15 16]
after transform:

# MODEL FITTING ON TRAIN DATA

In [80]:
logreg = LogisticRegression()
## fitiing the model
X = X_under_train[['V2','V3','V4','V9','V10','V11','V12','V14','V16','V17']]
logreg.fit(X, y_under_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [83]:
prediction = logreg.predict(X)
print(confusion_matrix(y_under_train,prediction))  
print(classification_report(y_under_train,prediction))
print(accuracy_score(y_under_train, prediction))

[[334   9]
 [ 34 311]]
             precision    recall  f1-score   support

          0       0.91      0.97      0.94       343
          1       0.97      0.90      0.94       345

avg / total       0.94      0.94      0.94       688

0.9375


# MODEL FITTING ON TEST DATA

In [84]:
## fitiing the model
X2 = X_under_test[['V2','V3','V4','V9','V10','V11','V12','V14','V16','V17']]
# logreg.fit(X2, y_under_test)

In [86]:
prediction2 = logreg.predict(X2)
print(confusion_matrix(y_under_test,prediction2))  
print(classification_report(y_under_test,prediction2))
print(accuracy_score(y_under_test, prediction2))

[[145   4]
 [ 11 136]]
             precision    recall  f1-score   support

          0       0.93      0.97      0.95       149
          1       0.97      0.93      0.95       147

avg / total       0.95      0.95      0.95       296

0.9493243243243243


# GRIDSEARCH ON TRAIN DATA

In [87]:
# Logistic regression
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler

logregpipe = Pipeline([('scale', StandardScaler()),
                   ('logreg',LogisticRegression(multi_class="multinomial",solver="lbfgs"))])

# Gridsearch to determine the value of C
param_grid = {'logreg__C':np.arange(0.01,100,10)}
logreg_cv = GridSearchCV(logregpipe,param_grid,cv=5,return_train_score=True)
logreg_cv.fit(X,y_under_train)
print(logreg_cv.best_params_)

bestlogreg = logreg_cv.best_estimator_
bestlogreg.fit(X,y_under_train)
bestlogreg.coef_ = bestlogreg.named_steps['logreg'].coef_
bestlogreg.score(X,y_under_train)

{'logreg__C': 10.01}


0.936046511627907

# GRIDSEARCH ON TEST DATA

In [88]:
bestlogreg = logreg_cv.best_estimator_
bestlogreg.fit(X2,y_under_test)
bestlogreg.coef_ = bestlogreg.named_steps['logreg'].coef_
bestlogreg.score(X2,y_under_test)

0.9628378378378378

# CROSS VALIATION ON TRAIN DATA

In [89]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn import cross_validation

predicted = cross_validation.cross_val_predict(LogisticRegression(),X,y_under_train, cv=10)
print (metrics.accuracy_score(y_under_train, predicted))

0.9302325581395349


# CROSS VALIDATION ON TEST DATA

In [90]:
predicted1 = cross_validation.cross_val_predict(LogisticRegression(),X2, y_under_test, cv=10)

print (metrics.classification_report(y_under_test, predicted1))
print (metrics.accuracy_score(y_under_test, predicted1))

             precision    recall  f1-score   support

          0       0.92      0.98      0.95       149
          1       0.98      0.92      0.95       147

avg / total       0.95      0.95      0.95       296

0.9493243243243243


# PCA ON LOGISTIC REGRESSION

In [91]:
pca = PCA(n_components=5)
X_under_train = pca.fit_transform(X_under_train)
X_under_test = pca.transform(X_under_test)
explained_variance = pca.explained_variance_ratio_
print(explained_variance)

[9.93983047e-01 4.15535766e-03 5.15372547e-04 4.96314732e-04
 2.27253703e-04]


# MODEL FITTING ON TRAIN & TEST DATA

In [92]:
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_under_train, y_under_train)
y_pred = classifier.predict(X_under_test)
print(confusion_matrix(y_under_test,y_pred))  
print(classification_report(y_under_test,y_pred)) 
print(accuracy_score(y_under_test, y_pred))

[[145   4]
 [ 16 131]]
             precision    recall  f1-score   support

          0       0.90      0.97      0.94       149
          1       0.97      0.89      0.93       147

avg / total       0.94      0.93      0.93       296

0.9324324324324325


# GRIDSEARCH ON TRAIN & TEST DATA

In [93]:
# Logistic regression
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler

logregpipe = Pipeline([('scale', StandardScaler()),
                   ('logreg',LogisticRegression(multi_class="multinomial",solver="lbfgs"))])

# Gridsearch to determine the value of C
param_grid = {'logreg__C':np.arange(0.01,100,10)}
logreg_cv = GridSearchCV(logregpipe,param_grid,cv=5,return_train_score=True)
logreg_cv.fit(X_under_train,y_under_train)
print(logreg_cv.best_params_)

bestlogreg = logreg_cv.best_estimator_
bestlogreg.fit(X_under_train,y_under_train)
bestlogreg.coef_ = bestlogreg.named_steps['logreg'].coef_
bestlogreg.score(X_under_train,y_under_train)

{'logreg__C': 50.01}


0.9418604651162791

# CROSS VALIDATION ON TEST & TRAIN DATA

In [94]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn import cross_validation

predicted = cross_validation.cross_val_predict(LogisticRegression(),X_under_train,y_under_train, cv=10)
print (metrics.accuracy_score(y_under_train, predicted))

0.9316860465116279


In [95]:
predicted1 = cross_validation.cross_val_predict(LogisticRegression(),X_under_test, y_under_test, cv=10)

print (metrics.classification_report(y_under_test, predicted1))
print (metrics.accuracy_score(y_under_test, predicted1))

             precision    recall  f1-score   support

          0       0.90      0.97      0.93       149
          1       0.97      0.88      0.93       147

avg / total       0.93      0.93      0.93       296

0.9290540540540541
