# IMPORTING LIBRARIES

In [1]:
import pandas as pd
import numpy as np
import imblearn
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFE
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn import linear_model
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import PCA
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, accuracy_score, classification_report, confusion_matrix

# READING CSV FILE

In [2]:
data = pd.read_csv("./CC.csv")
data.head()

Unnamed: 0  Time        V1        V2        V3        V4        V5  \
0           1   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321   
1           2   0.0  1.191857  0.266151  0.166480  0.448154  0.060018   
2           3   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198   
3           4   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309   
4           5   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193   

         V6        V7        V8  ...         V21       V22       V23  \
0  0.462388  0.239599  0.098698  ...   -0.018307  0.277838 -0.110474   
1 -0.082361 -0.078803  0.085102  ...   -0.225775 -0.638672  0.101288   
2  1.800499  0.791461  0.247676  ...    0.247998  0.771679  0.909412   
3  1.247203  0.237609  0.377436  ...   -0.108300  0.005274 -0.190321   
4  0.095921  0.592941 -0.270533  ...   -0.009431  0.798278 -0.137458   

        V24       V25       V26       V27       V28  Amount  Class  
0  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62      0  
1 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69      0  
2 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0  
3 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50      0  
4  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 32 columns]

In [3]:
# now let us check in the number of Percentage
Count_Normal_transacation = len(data[data["Class"]==0]) # normal transaction are repersented by 0
Count_Fraud_transacation = len(data[data["Class"]==1]) # fraud by 1
Percentage_of_Normal_transacation = Count_Normal_transacation/(Count_Normal_transacation+Count_Fraud_transacation)
print("percentage of normal transacation is",Percentage_of_Normal_transacation*100)
Percentage_of_Fraud_transacation= Count_Fraud_transacation/(Count_Normal_transacation+Count_Fraud_transacation)
print("percentage of fraud transacation",Percentage_of_Fraud_transacation*100)


percentage of normal transacation is 99.82725143693798
percentage of fraud transacation 0.1727485630620034


In [4]:
print("length of training data",len(data))
print("length of normal data",len(data[data["Class"]==0]))
print("length of fraud  data",len(data[data["Class"]==1]))

length of training data 284807
length of normal data 284315
length of fraud  data 492


In [5]:
X = data[['V1','V2','V3','V4','V5','V6','V7','V8','V9','V10','V11','V12','V13','V14','V15','V16','V17','V18','V19',
          'V20','V21','V22','V23','V24','V25','V26','V27','V28','Amount']]
Y = data['Class']

# Oversampling the data

In [6]:
from imblearn.over_sampling import SMOTE

os = SMOTE(random_state=0) 
columns = X.columns

os_data_X,os_data_y=os.fit_sample(X,Y)
os_data_X = pd.DataFrame(data=os_data_X,columns=columns )
os_data_y= pd.DataFrame(data=os_data_y,columns=["Class"])
# we can Check the numbers of our data
print("length of oversampled data is ",len(os_data_X))
print("Number of normal transcation in oversampled data",len(os_data_y[os_data_y["Class"]==0]))
print("No.of fraud transcation",len(os_data_y[os_data_y["Class"]==1]))
print("Proportion of Normal data in oversampled data is ",len(os_data_y[os_data_y["Class"]==0])/len(os_data_X))
print("Proportion of fraud data in oversampled data is ",len(os_data_y[os_data_y["Class"]==1])/len(os_data_X))

length of oversampled data is  568630
Number of normal transcation in oversampled data 284315
No.of fraud transcation 284315
Proportion of Normal data in oversampled data is  0.5
Proportion of fraud data in oversampled data is  0.5


In [7]:
os_data_X

V1         V2         V3         V4         V5        V6  \
0       -1.359807  -0.072781   2.536347   1.378155  -0.338321  0.462388   
1        1.191857   0.266151   0.166480   0.448154   0.060018 -0.082361   
2       -1.358354  -1.340163   1.773209   0.379780  -0.503198  1.800499   
3       -0.966272  -0.185226   1.792993  -0.863291  -0.010309  1.247203   
4       -1.158233   0.877737   1.548718   0.403034  -0.407193  0.095921   
5       -0.425966   0.960523   1.141109  -0.168252   0.420987 -0.029728   
6        1.229658   0.141004   0.045371   1.202613   0.191881  0.272708   
7       -0.644269   1.417964   1.074380  -0.492199   0.948934  0.428118   
8       -0.894286   0.286157  -0.113192  -0.271526   2.669599  3.721818   
9       -0.338262   1.119593   1.044367  -0.222187   0.499361 -0.246761   
10       1.449044  -1.176339   0.913860  -1.375667  -1.971383 -0.629152   
11       0.384978   0.616109  -0.874300  -0.094019   2.924584  3.317027   
12       1.249999  -1.221637   0.383930  -1.234899  -1.485419 -0.753230   
13       1.069374   0.287722   0.828613   2.712520  -0.178398  0.337544   
14      -2.791855  -0.327771   1.641750   1.767473  -0.136588  0.807596   
15      -0.752417   0.345485   2.057323  -1.468643  -1.158394 -0.077850   
16       1.103215  -0.040296   1.267332   1.289091  -0.735997  0.288069   
17      -0.436905   0.918966   0.924591  -0.727219   0.915679 -0.127867   
18      -5.401258  -5.450148   1.186305   1.736239   3.049106 -1.763406   
19       1.492936  -1.029346   0.454795  -1.438026  -1.555434 -0.720961   
20       0.694885  -1.361819   1.029221   0.834159  -1.191209  1.309109   
21       0.962496   0.328461  -0.171479   2.109204   1.129566  1.696038   
22       1.166616   0.502120  -0.067300   2.261569   0.428804  0.089474   
23       0.247491   0.277666   1.185471  -0.092603  -1.314394 -0.150116   
24      -1.946525  -0.044901  -0.405570  -1.013057   2.941968  2.955053   
25      -2.074295  -0.121482   1.322021   0.410008   0.295198 -0.959537   
26       1.173285   0.353498   0.283905   1.133563  -0.172577 -0.916054   
27       1.322707  -0.174041   0.434555   0.576038  -0.836758 -0.831083   
28      -0.414289   0.905437   1.727453   1.473471   0.007443 -0.200331   
29       1.059387  -0.175319   1.266130   1.186110  -0.786002  0.578435   
...           ...        ...        ...        ...        ...       ...   
568600  -0.431850   1.740233  -1.287095   3.812569  -1.319112 -0.555231   
568601   1.141351   2.261760  -4.341890   5.415610   0.478417 -1.125233   
568602  -5.416994   5.170464  -7.532386   7.952700  -2.700946 -1.626737   
568603  -1.626548   1.004557  -1.560578   2.785502  -2.510142 -0.361643   
568604  -0.565370   1.312136  -3.436349   1.866344  -0.256212 -2.177116   
568605  -7.446569  -7.323783  -4.002447   3.645846   5.737345 -6.054929   
568606  -3.159428   3.079884  -5.377163   5.722466  -2.313808 -1.643678   
568607  -1.450912   2.135279  -1.279962   1.232791  -0.433712 -1.356919   
568608   1.209434   2.577845  -5.370135   5.331441   1.262602 -1.342694   
568609  -1.438377  -3.069143  -6.433362   3.423775  -1.300889 -1.509051   
568610  -0.956192   1.975265  -1.937979   2.098744  -1.108404 -1.237650   
568611  -3.189151   2.365126  -4.019560   0.494608  -2.187439 -1.725685   
568612 -27.974616  15.650318 -29.025672   6.423893 -20.428470 -4.835199   
568613  -1.255264   2.465390  -2.875635   2.367229  -1.366626 -0.947491   
568614  -1.091079  -0.973877  -0.733176   0.621101   7.879658 -4.031369   
568615   1.224977   2.560976  -5.028949   5.369525   1.097473 -1.335297   
568616  -1.006315   1.306498  -0.478097   2.179963  -1.087580 -0.118490   
568617  -0.691588   0.618486   1.019345  -0.217790  -0.564045 -0.609945   
568618   0.244960   4.234850  -6.855685   7.329051   0.705109 -2.714794   
568619 -17.007426   9.737082 -23.810473  11.822667  -9.886202 -2.527396   
568620  -7.232802   5.318540  -9.339838   7.518170  -7.436339 -2.707816   
568621   1.882212   1.237328  -2.104280 

# SPLITTING THE DATASET INTO TRAIN AND TEST

In [8]:
X_over = os_data_X[['V1','V2','V3','V4','V5','V6','V7','V8','V9','V10','V11','V12','V13','V14','V15','V16','V17','V18','V19',
               'V20','V21','V22','V23','V24','V25','V26','V27','V28','Amount']]
y_over = os_data_y['Class']

In [9]:
y_over

0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0
23        0
24        0
25        0
26        0
27        0
28        0
29        0
         ..
568600    1
568601    1
568602    1
568603    1
568604    1
568605    1
568606    1
568607    1
568608    1
568609    1
568610    1
568611    1
568612    1
568613    1
568614    1
568615    1
568616    1
568617    1
568618    1
568619    1
568620    1
568621    1
568622    1
568623    1
568624    1
568625    1
568626    1
568627    1
568628    1
568629    1
Name: Class, Length: 568630, dtype: int64

In [10]:

X_over_train, X_over_test, y_over_train, y_over_test = train_test_split(X_over,y_over,test_size = 0.3, random_state = 0)

# RFE ON SVM

In [ ]:
from sklearn.svm import SVC  

model = SVC(kernel='linear')
rfe = RFE(model)
fit = rfe.fit(X_over_train,y_over_train)


In [ ]:
print("Number of Features: %d"% fit.n_features_)
print("Selected features: %s"% fit.support_)
print("Ranking of features: %s"% fit.ranking_)  

# MODEL FITTING ON TRAIN DATA

In [14]:
X = X_over_train[['V1','V2','V3','V4','V5','V8','V10','V11','V12','V14','V16','V17','V18','Amount']]

In [17]:
model.fit(X, y_over_train)  
y_pred = model.predict(X)  
print(confusion_matrix(y_over_train,y_pred))  
print(classification_report(y_over_train,y_pred)) 
print(accuracy_score(y_over_train, y_pred))

[[199137      6]
 [     0 198898]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00    199143
          1       1.00      1.00      1.00    198898

avg / total       1.00      1.00      1.00    398041

0.9999849261759467


## Test data accuracy

In [18]:
# regressor = RandomForestClassifier(n_estimators=20, random_state=0)  
X2 = X_over_test[['V1','V2','V3','V4','V5','V8','V10','V11','V12','V14','V16','V17','V18','Amount']]
# regressor.fit(X2, y_under_test)  
y_pred = model.predict(X2)  
print(confusion_matrix(y_over_test,y_pred))  
print(classification_report(y_over_test,y_pred))  
print(accuracy_score(y_over_test, y_pred))  

[[85147    25]
 [   13 85404]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00     85172
          1       1.00      1.00      1.00     85417

avg / total       1.00      1.00      1.00    170589

0.999777242377879


## Grid search 

In [35]:
from sklearn.grid_search import GridSearchCV
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
# Build a classification task using 3 informative features
X, y_over_train = make_classification(n_samples=50,
                                      n_features=10,
                                      n_informative=3,
                                      n_redundant=0,
                                      n_repeated=0,
                                      n_classes=2,
                                      random_state=0,
                                      shuffle=False)


rfc = RandomForestClassifier(n_jobs=-1,max_features= 'sqrt' ,n_estimators=50, oob_score = True) 

param_grid = { 
    'n_estimators': [200, 700],
    'max_features': ['auto', 'sqrt', 'log2']
}

CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
CV_rfc.fit(X, y_over_train)
print (CV_rfc.best_params_)

C:\Users\Komal\AppData\Roaming\Python\Python37\site-packages\sklearn\grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


{'max_features': 'sqrt', 'n_estimators': 200}


In [36]:
CV_rfc.score(X, y_over_train)

1.0

In [37]:

CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
CV_rfc.fit(X2, y_over_test)
print (CV_rfc.best_params_)

{'max_features': 'auto', 'n_estimators': 200}


In [38]:
CV_rfc.score(X2, y_over_test)

1.0

In [58]:
y_over_train


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [56]:
X

V3        V4        V9        V10       V11        V12  \
212637  -0.867900 -0.534643 -0.181912  -1.056287 -1.050413  -0.090738   
535831  -2.010618  4.228306 -1.234631  -2.424904  2.713344  -5.654222   
182914   0.335179 -0.246120 -0.527933  -0.723643 -1.934401  -1.112214   
402648  -4.772336  3.235866 -0.823270  -5.377625  5.524205  -7.234969   
80440    1.157308 -0.183143 -0.685132  -0.395156  1.470742   0.761061   
47452    0.611499 -0.516958  0.110167   0.262034 -1.371733  -0.217701   
225669  -3.582175  1.337566  1.133534  -0.307708  1.259998   0.441839   
190802  -0.382970 -0.739292 -1.621996   0.325129 -0.209041   0.083971   
138519   0.054452 -3.433765 -0.407771  -1.169569  0.866920   1.487880   
259226  -0.510240 -0.439358  0.245697   0.823936  0.102827   0.200951   
388471  -0.277175  0.782622 -0.247372  -0.385891  1.309659  -0.089804   
146435   0.110152 -0.957901  0.059777  -0.475257 -0.775989   0.448596   
537981  -4.009130  1.454796  1.284267  -1.751056 -1.047255  -0.415174   
121685   2.072731  0.047881 -0.038616  -1.115329  0.079973   1.026025   
143495   1.698626  0.046575 -0.408340  -0.312048 -0.118468   0.021864   
222250  -0.975188 -0.649073 -0.306906  -0.273132  0.318431   0.921031   
314979   1.093298  0.888481 -0.330323  -0.841985  0.678439  -0.649273   
343526  -3.018672  0.175436  0.091667  -3.067196  2.623642  -3.726418   
310484  -3.050702  4.117337 -2.650370  -5.179149  4.056365  -8.110217   
379177  -3.920415  2.205956  0.152185  -3.816640  4.084405  -4.780589   
97104    0.705545 -0.911486 -1.683595   0.934309  1.543540  -0.619697   
338781  -9.906650  3.320337 -0.391540  -5.052502  4.406806  -4.610756   
93062    0.725124 -0.903208  0.232292  -0.715828  0.443928   0.190631   
397949 -14.217718  8.341413 -4.940015 -14.129898  7.663885 -15.195525   
231946   0.382449 -0.188349  0.616514   0.600604 -1.111969   0.510259   
433668  -8.881005  7.857222 -3.839231  -8.205695  7.524614 -10.201581   
44077    1.262189 -1.777464 -1.917122   0.072482  1.112731   0.335402   
114739   0.151227  0.014069 -0.963191   0.274286  1.816930   0.102830   
522948  -2.694235  2.528364 -1.477259  -3.412473  2.191565  -2.652727   
96054    1.399213  0.166769 -0.642806  -0.756097  0.712200   1.095568   
...           ...       ...       ...        ...       ...        ...   
514591  -2.570961  3.844049 -2.593731  -3.793894  3.153988  -5.548875   
303648  -4.442307  2.664032 -1.287778  -6.630715  6.192563  -8.375480   
381567 -13.546560  4.308963 -2.357217  -5.983408  2.566613  -5.929303   
84665    0.201589  0.954071 -0.035783  -0.084136 -0.490540   0.553568   
183561   0.102928 -0.510517  1.253453   0.202938  0.379784   0.605379   
122144   1.825084 -1.969706 -2.264709   1.147601 -0.513015  -1.359207   
473998   0.238655  1.629848 -0.133714  -0.190972  1.067124  -1.194187   
49811    1.169120  1.269672 -0.836996  -0.200976  1.210110   1.373879   
230131  -0.287665  0.240216  1.357618  -0.257694 -0.511184   0.976068   
556209  -0.576937  2.107489  0.035283  -1.481841  0.457117  -1.504054   
370648  -4.478104  4.607667 -1.811400  -1.804633  2.304397  -5.567403   
441170  -4.009053  3.556401 -1.003685  -2.170653  0.894241  -1.400112   
346110  -1.461360  2.071503  0.174424  -2.115101  0.847013  -0.683550   
532165  -5.585454  3.806944 -3.024652  -6.394338  4.129067  -6.532914   
430835  -2.298877  2.533602 -1.401625  -4.662374  2.834798  -2.657773   
332752   0.048150  2.435065 -0.697833  -0.158520  2.791664  -2.543633   
255653  -1.943810  0.283312  0.589881  -0.373975 -1.079366  -0.224722   
370775  -6.612325  6.746604 -2.370393  -4.656084  4.612979  -7.736554   
541377  -5.142273  5.363239 -2.659792  -3.112624  2.962643  -3.822542   
170584  -2.391905  1.063847 -0.098435   0.313477 -1.390943  -0.199977   
310744  -2.599945 -0.332914  0.087577  -3.989717  2.364804  -3.379804   
374564  -5.667332  2.158273 -1.865329  -3.924081  1.072900  -3.795942   
448242   0.896622  0.864666 -0.212287  -0.812023  0.387327  -0.686482   


# K BEST ON Random Forest

In [82]:
#array = under_sample.values
test = SelectKBest(score_func=f_classif, k=10)
fit = test.fit(X_over_train, y_over_train)
print("scores_:",test.scores_)
print("pvalues_:",test.pvalues_)
print("selected index:",test.get_support(True))
print("after transform:",test.transform(X_over_train)) 

scores_: [8.90094295e+04 1.34490388e+05 1.88238248e+05 4.20919510e+05
 7.01624088e+04 8.27595776e+04 1.17168375e+05 2.23421604e+03
 2.02211994e+05 2.80165278e+05 3.89901322e+05 3.69625988e+05
 1.92694387e+03 5.77083297e+05 5.09794479e+02 2.29924455e+05
 1.94388512e+05 1.19822984e+05 3.01968294e+04 1.46847404e+04
 7.76561530e+03 1.42699446e+01 6.32743066e+01 4.76825994e+03
 1.19644623e+03 1.45353018e+03 4.46225074e+03 4.20967142e+03
 1.73454612e+03]
pvalues_: [0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 0.00000000e+000 8.28014570e-113 0.00000000e+000
 0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000
 0.00000000e+000 1.58396646e-004 1.80301758e-015 0.00000000e+000
 8.87098339e-262 1.84523094e-317 0.00000000e+000 0.00000000e+000
 0.00000000e+000]
selected index: [ 1  2  3  8  9 10 11 13 15 16]
after transform:

# MODEL FITTING ON TRAIN DATA

## Training Accuracy

In [83]:
model = RandomForestClassifier()
X = X_over_train[['V2','V3','V4','V9','V10','V11','V12','V14','V16','V17']]
model.fit(X, y_over_train)
y_pred = model.predict(X)
print(confusion_matrix(y_over_train,y_pred))  
print(classification_report(y_over_train,y_pred))  
print(accuracy_score(y_over_train, y_pred))


[[199141      2]
 [     3 198895]]
             precision    recall  f1-score   support

          0       1.00      1.00      1.00    199143
          1       1.00      1.00      1.00    198898

avg / total       1.00      1.00      1.00    398041

0.9999874384799556


# MODEL FITTING ON TEST DATA

In [86]:
## fitiing the model
X2 = X_over_test[['V2','V3','V4','V9','V10','V11','V12','V14','V16','V17']]
# logreg.fit(X2, y_under_test)

In [87]:

classifier = LogisticRegression(random_state = 0)
classifier.fit(X2, y_over_test)
y_pred = classifier.predict(X2)
print(confusion_matrix(y_over_test,y_pred))  
print(classification_report(y_over_test,y_pred)) 
print(accuracy_score(y_over_test, y_pred))


[[83454  1718]
 [ 6623 78794]]
             precision    recall  f1-score   support

          0       0.93      0.98      0.95     85172
          1       0.98      0.92      0.95     85417

avg / total       0.95      0.95      0.95    170589

0.9511047019444395


## Grid Search

In [88]:
from sklearn.grid_search import GridSearchCV
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
# Build a classification task using 3 informative features
X, y_over_train = make_classification(n_samples=50,
                                      n_features=10,
                                      n_informative=3,
                                      n_redundant=0,
                                      n_repeated=0,
                                      n_classes=2,
                                      random_state=0,
                                      shuffle=False)


rfc = RandomForestClassifier(n_jobs=-1,max_features= 'sqrt' ,n_estimators=50, oob_score = True) 

param_grid = { 
    'n_estimators': [200, 700],
    'max_features': ['auto', 'sqrt', 'log2']
}

CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
CV_rfc.fit(X, y_over_train)
print (CV_rfc.best_params_)

{'max_features': 'sqrt', 'n_estimators': 200}


In [89]:
CV_rfc.score(X, y_over_train)

1.0

In [ ]:
CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
CV_rfc.fit(X2, y_over_test)
print (CV_rfc.best_params_)

In [ ]:
CV_rfc.score(X2, y_over_test)

# PCA ON LOGISTIC REGRESSION

In [ ]:
pca = PCA(n_components=5)
X_over_train = pca.fit_transform(X_over_train)
X_over_test = pca.transform(X_over_test)
explained_variance = pca.explained_variance_ratio_
print(explained_variance)

# MODEL FITTING ON TRAIN & TEST DATA

In [59]:
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_under_train, y_under_train)
y_pred = classifier.predict(X_under_test)
print(confusion_matrix(y_under_test,y_pred))  
print(classification_report(y_under_test,y_pred)) 
print(accuracy_score(y_under_test, y_pred))

[[147   2]
 [ 16 131]]
             precision    recall  f1-score   support

          0       0.90      0.99      0.94       149
          1       0.98      0.89      0.94       147

avg / total       0.94      0.94      0.94       296

0.9391891891891891
