# IMPORTING LIBRARIES

In [2]:
import pandas as pd
import numpy as np
import imblearn
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFE
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn import linear_model
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, accuracy_score, classification_report, confusion_matrix
from sklearn.svm import SVC  
from sklearn.decomposition import PCA


# READING CSV FILE

In [3]:
df = pd.read_csv("./creditcard.csv")
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...         V21       V22       V23       V24  \
0  0.098698  0.363787  ...   -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425  ...   -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  ...    0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024  ...   -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  ...   -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Amount  Class  
0  0.128539 -0.189115  0.133558 -0.021053  149.62      0  
1  0.167170  0.125895 -0.008983  0.014724    2.69      0  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0  
3  0.647376 -0.221929  0.062723  0.061458  123.50      0  
4 -0.206010  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

# UNDERSAMPLING THE DATA

In [4]:
no_frauds = len(df[df['Class'] == 1])
non_fraud_indices = df[df.Class == 0].index
non_fraud_indices = df[df.Class == 0].index
random_indices = np.random.choice(non_fraud_indices, no_frauds, replace=False)
fraud_indices = df[df.Class == 1].index
under_sample_indices = np.concatenate([fraud_indices,random_indices])
under_sample = df.loc[under_sample_indices]

# UNDERSAMPLED DATASET

In [5]:
under_sample

Time        V1        V2         V3        V4        V5        V6  \
541        406.0 -2.312227  1.951992  -1.609851  3.997906 -0.522188 -1.426545   
623        472.0 -3.043541 -3.157307   1.088463  2.288644  1.359805 -1.064823   
4920      4462.0 -2.303350  1.759247  -0.359745  2.330243 -0.821628 -0.075788   
6108      6986.0 -4.397974  1.358367  -2.592844  2.679787 -1.128131 -1.706536   
6329      7519.0  1.234235  3.019740  -4.304597  4.732795  3.624201 -1.357746   
6331      7526.0  0.008430  4.137837  -6.240697  6.675732  0.768307 -3.353060   
6334      7535.0  0.026779  4.132464  -6.560600  6.348557  1.329666 -2.513479   
6336      7543.0  0.329594  3.712889  -5.775935  6.078266  1.667359 -2.420168   
6338      7551.0  0.316459  3.809076  -5.615159  6.047445  1.554026 -2.651353   
6427      7610.0  0.725646  2.300894  -5.329976  4.007683 -1.730411 -1.732193   
6446      7672.0  0.702710  2.426433  -5.234513  4.416661 -2.170806 -2.667554   
6472      7740.0  1.023874  2.001485  -4.769752  3.819195 -1.271754 -1.734662   
6529      7891.0 -1.585505  3.261585  -4.137422  2.357096 -1.405043 -1.879437   
6609      8090.0 -1.783229  3.402794  -3.822742  2.625368 -1.976415 -2.731689   
6641      8169.0  0.857321  4.093912  -7.423894  7.380245  0.973366 -2.730762   
6717      8408.0 -1.813280  4.917851  -5.926130  5.701500  1.204393 -3.035138   
6719      8415.0 -0.251471  4.313523  -6.891438  6.796797  0.616297 -2.966327   
6734      8451.0  0.314597  2.660670  -5.920037  4.522500 -2.315027 -2.278352   
6774      8528.0  0.447396  2.481954  -5.660814  4.455923 -2.443780 -2.185040   
6820      8614.0 -2.169929  3.639654  -4.508498  2.730668 -2.122693 -2.341017   
6870      8757.0 -1.863756  3.442644  -4.468260  2.805336 -2.118412 -2.332285   
6882      8808.0 -4.617217  1.695694  -3.114372  4.328199 -1.873257 -0.989908   
6899      8878.0 -2.661802  5.856393  -7.653616  6.379742 -0.060712 -3.131550   
6903      8886.0 -2.535852  5.793644  -7.618463  6.395830 -0.065210 -3.136372   
6971      9064.0 -3.499108  0.258555  -4.489558  4.853894 -6.974522  3.628382   
8296     11080.0 -2.125490  5.973556 -11.034727  9.007147 -1.689451 -2.854415   
8312     11092.0  0.378275  3.914797  -5.726872  6.094141  1.698875 -2.807314   
8335     11131.0 -1.426623  4.141986  -9.804103  6.666273 -4.749527 -2.073129   
8615     11629.0 -3.891192  7.098916 -11.426467  8.607557 -2.065706 -2.985288   
8617     11635.0  0.919137  4.199633  -7.535607  7.426940  1.118215 -2.886722   
...          ...       ...       ...        ...       ...       ...       ...   
222598  143046.0  1.556462 -1.382022  -0.760610 -0.520950 -1.112919 -0.819675   
125631   77738.0 -0.743064  1.239650   0.864514  0.131088 -0.438319 -0.987888   
207936  136898.0 -1.094941  0.534705  -3.554132  0.758139  0.309346  1.857530   
12256    21411.0 -4.163723 -5.046474  -0.340486 -0.733643  1.593015  3.758657   
260555  159615.0  1.504422 -1.125329   0.142813  1.372838 -1.150032  0.520666   
84584    60377.0  1.001220 -0.490417   1.678707  1.242191 -1.253258  0.568052   
88014    61947.0 -1.315092 -5.023820  -1.513669  0.640823 -2.330276 -0.616211   
189932  128616.0  2.140377 -1.712569  -0.423130 -1.555009 -1.599008 -0.053522   
154970  103850.0  1.854764  0.389515   0.177952  3.930358  0.122777  0.755156   
221242  142490.0 -0.590127  1.251231  -0.898570 -0.513272  0.775759 -0.855400   
189612  128482.0 -0.019910  0.603059   0.351533 -1.323018  1.061353 -1.302212   
79380    57995.0  1.012532 -1.042541   0.542201 -0.699690 -0.690147  0.953671   
75893    56294.0  0.957887 -0.348749  -0.232951  1.557067  1.632335  4.357163   
94068    64712.0  1.283632 -0.009924   0.191624 -0.255859 -0.388690 -0.697600   
37553    39006.0  1.205726  0.304113   0.145672  1.194031  0.012849 -0.418032   
188481  127993.0  1.968320 -0.423465  -0.266977  0.524970 -0.791209 -0.576371   
3256      2807.0  1.238537 -0.012364   0.183865 -0.799180 -0.572495 -1.307395   
205870  135949.0 -0.388308  0.988328   0.14

# SPLITTING THE DATASET INTO TRAIN AND TEST

In [6]:
X_under = under_sample[['V1','V2','V3','V4','V5','V6','V7','V8','V9','V10','V11','V12','V13','V14','V15','V16','V17','V18','V19',
                        'V20','V21','V22','V23','V24','V25','V26','V27','V28','Amount']]
y_under = under_sample['Class']
X_under_train, X_under_test, y_under_train, y_under_test = train_test_split(X_under,y_under,test_size = 0.3, random_state = 0)

# RFE ON SVM

In [7]:
model = SVC(kernel='linear')
rfe = RFE(model)
fit = rfe.fit(X_under_train,y_under_train)
print("Number of Features: %d"% fit.n_features_)
print("Selected features: %s"% fit.support_)
print("Ranking of features: %s"% fit.ranking_)  

Number of Features: 14
Selected features: [False  True False  True  True False  True  True False  True  True  True
 False  True False  True  True False False False False False  True False
  True False  True False False]
Ranking of features: [ 4  1 14  1  1 10  1  1 15  1  1  1  5  1  3  1  1  7 13 12 11  8  1  9
  1  6  1  2 16]


# MODEL FITTING ON TRAIN DATA

In [8]:
svclassifier = SVC(kernel='linear')  
X = X_under_train[['V4','V6','V8','V9','V10','V11','V12','V14','V16','V17','V18','V21','V22','V23','V27']]
svclassifier.fit(X, y_under_train)
y_pred = svclassifier.predict(X)
print(confusion_matrix(y_under_train,y_pred))  
print(classification_report(y_under_train,y_pred))  
print(accuracy_score(y_under_train, y_pred))


[[339   4]
 [ 33 312]]
             precision    recall  f1-score   support

          0       0.91      0.99      0.95       343
          1       0.99      0.90      0.94       345

avg / total       0.95      0.95      0.95       688

0.9462209302325582


# MODEL FITTING ON TEST DATA

In [9]:
X2 = X_under_test[['V4','V6','V8','V9','V10','V11','V12','V14','V16','V17','V18','V21','V22','V23','V27']]
y_pred = svclassifier.predict(X2)
print(confusion_matrix(y_under_test,y_pred))  
print(classification_report(y_under_test,y_pred))  
print(accuracy_score(y_under_test, y_pred))


[[145   4]
 [ 16 131]]
             precision    recall  f1-score   support

          0       0.90      0.97      0.94       149
          1       0.97      0.89      0.93       147

avg / total       0.94      0.93      0.93       296

0.9324324324324325


# GRIDSEARCH ON TRAIN DATA

In [10]:
# Logistic regression
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler

logregpipe = Pipeline([('scale', StandardScaler()),
                   ('logreg',LogisticRegression(multi_class="multinomial",solver="lbfgs"))])

# Gridsearch to determine the value of C
param_grid = {'logreg__C':np.arange(0.01,100,10)}
logreg_cv = GridSearchCV(logregpipe,param_grid,cv=5,return_train_score=True)
logreg_cv.fit(X,y_under_train)
print(logreg_cv.best_params_)

bestlogreg = logreg_cv.best_estimator_
bestlogreg.fit(X,y_under_train)
bestlogreg.coef_ = bestlogreg.named_steps['logreg'].coef_
bestlogreg.score(X,y_under_train)

{'logreg__C': 10.01}


0.9462209302325582

# GRIDSEARCH ON TEST DATA

In [11]:
bestlogreg = logreg_cv.best_estimator_
bestlogreg.fit(X2,y_under_test)
bestlogreg.coef_ = bestlogreg.named_steps['logreg'].coef_
bestlogreg.score(X2,y_under_test)

0.956081081081081

# CROSS VALIDATION ON TRAIN DATA

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn import cross_validation

predicted = cross_validation.cross_val_predict(LogisticRegression(),X,y_under_train, cv=10)
print (metrics.accuracy_score(y_under_train, predicted))

0.936046511627907


C:\Users\sayal\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


# CROSS VALIDATION ON TEST DATA

In [13]:
predicted1 = cross_validation.cross_val_predict(LogisticRegression(),X2, y_under_test, cv=10)

print (metrics.classification_report(y_under_test, predicted1))
print (metrics.accuracy_score(y_under_test, predicted1))

             precision    recall  f1-score   support

          0       0.92      0.95      0.93       149
          1       0.94      0.91      0.93       147

avg / total       0.93      0.93      0.93       296

0.9290540540540541


# K BEST ON SVM

In [14]:
array = under_sample.values
test = SelectKBest(score_func=f_classif, k=10)
fit = test.fit(X_under_train, y_under_train)

In [15]:
print("scores_:",test.scores_)
print("pvalues_:",test.pvalues_)
print("selected index:",test.get_support(True))
print("after transform:",test.transform(X_under_train)) 

scores_: [1.82273231e+02 2.50407484e+02 3.48339250e+02 6.75688177e+02
 1.08532650e+02 1.38417108e+02 2.25323506e+02 4.67443081e+00
 2.94612681e+02 4.95293789e+02 6.09895990e+02 6.24717094e+02
 2.20928935e-01 9.15064350e+02 9.07914006e-01 3.87729746e+02
 3.18844720e+02 1.90319957e+02 6.09530327e+01 1.63007782e+01
 2.25057636e+01 9.19749844e-01 2.79064715e+00 9.38206817e+00
 2.73693615e+00 1.82046511e-01 1.12577179e+01 2.42282666e+00
 2.35402548e+00]
pvalues_: [5.25127514e-037 2.60037100e-048 3.53570962e-063 3.20389971e-104
 1.07853663e-023 3.08160131e-029 2.99661564e-044 3.09599033e-002
 3.30226950e-055 5.15112700e-083 7.83756883e-097 1.57557592e-098
 6.38482410e-001 2.24690105e-128 3.41004109e-001 9.24453036e-069
 7.42612176e-059 2.18186235e-038 2.19030487e-014 6.01345771e-005
 2.55012066e-006 3.37878542e-001 9.52720675e-002 2.27694045e-003
 9.85100377e-002 6.69754231e-001 8.36602350e-004 1.20040182e-001
 1.25420999e-001]
selected index: [ 1  2  3  8  9 10 11 13 15 16]
after transform:

# MODEL FITTING ON TRAIN DATA

In [16]:
svclassifier = SVC(kernel='linear')  
X = X_under_train[['V2','V3','V4','V9','V10','V11','V12','V14','V16','V17']]
svclassifier.fit(X, y_under_train)
y_pred = svclassifier.predict(X)
print(confusion_matrix(y_under_train,y_pred))  
print(classification_report(y_under_train,y_pred))  
print(accuracy_score(y_under_train, y_pred))


[[338   5]
 [ 38 307]]
             precision    recall  f1-score   support

          0       0.90      0.99      0.94       343
          1       0.98      0.89      0.93       345

avg / total       0.94      0.94      0.94       688

0.9375


# MODEL FITTING ON TEST DATA

In [17]:
X2 = X_under_test[['V2','V3','V4','V9','V10','V11','V12','V14','V16','V17']]
y_pred = svclassifier.predict(X2)
print(confusion_matrix(y_under_test,y_pred))  
print(classification_report(y_under_test,y_pred))  
print(accuracy_score(y_under_test, y_pred))


[[148   1]
 [ 14 133]]
             precision    recall  f1-score   support

          0       0.91      0.99      0.95       149
          1       0.99      0.90      0.95       147

avg / total       0.95      0.95      0.95       296

0.9493243243243243


# GRIDSEARCH ON TRAIN DATA

In [18]:
# Logistic regression
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler

logregpipe = Pipeline([('scale', StandardScaler()),
                   ('logreg',LogisticRegression(multi_class="multinomial",solver="lbfgs"))])

# Gridsearch to determine the value of C
param_grid = {'logreg__C':np.arange(0.01,100,10)}
logreg_cv = GridSearchCV(logregpipe,param_grid,cv=5,return_train_score=True)
logreg_cv.fit(X,y_under_train)
print(logreg_cv.best_params_)

bestlogreg = logreg_cv.best_estimator_
bestlogreg.fit(X,y_under_train)
bestlogreg.coef_ = bestlogreg.named_steps['logreg'].coef_
bestlogreg.score(X,y_under_train)

{'logreg__C': 70.01}


0.9433139534883721

# GRIDSEARCH ON TEST DATA

In [19]:
bestlogreg = logreg_cv.best_estimator_
bestlogreg.fit(X2,y_under_test)
bestlogreg.coef_ = bestlogreg.named_steps['logreg'].coef_
bestlogreg.score(X2,y_under_test)

0.9594594594594594

# CROSS VALIDATION ON TRAIN DATA

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn import cross_validation

predicted = cross_validation.cross_val_predict(LogisticRegression(),X,y_under_train, cv=10)
print (metrics.accuracy_score(y_under_train, predicted))

0.9375


# CROSS VALIDATION ON TEST DATA

In [21]:
predicted1 = cross_validation.cross_val_predict(LogisticRegression(),X2, y_under_test, cv=10)

print (metrics.classification_report(y_under_test, predicted1))
print (metrics.accuracy_score(y_under_test, predicted1))

             precision    recall  f1-score   support

          0       0.91      0.96      0.93       149
          1       0.96      0.90      0.93       147

avg / total       0.93      0.93      0.93       296

0.9324324324324325


# PCA ON SVM

In [22]:
pca = PCA(n_components=5)
X_under_train = pca.fit_transform(X_under_train)
X_under_test = pca.transform(X_under_test)
explained_variance = pca.explained_variance_ratio_
print(explained_variance)

[9.94439738e-01 3.85079607e-03 4.69598485e-04 4.51920920e-04
 2.12195813e-04]


# MODEL FITTING ON TRAIN & TEST DATA

In [23]:
svclassifier = SVC(kernel='linear')  
svclassifier.fit(X_under_train, y_under_train)
y_pred = svclassifier.predict(X_under_test)
print(confusion_matrix(y_under_test,y_pred))  
print(classification_report(y_under_test,y_pred)) 
print(accuracy_score(y_under_test, y_pred))


[[147   2]
 [ 14 133]]
             precision    recall  f1-score   support

          0       0.91      0.99      0.95       149
          1       0.99      0.90      0.94       147

avg / total       0.95      0.95      0.95       296

0.9459459459459459


# GRIDSEARCH ON TEST & TRAIN DATA

In [24]:
# Logistic regression
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler

logregpipe = Pipeline([('scale', StandardScaler()),
                   ('logreg',LogisticRegression(multi_class="multinomial",solver="lbfgs"))])

# Gridsearch to determine the value of C
param_grid = {'logreg__C':np.arange(0.01,100,10)}
logreg_cv = GridSearchCV(logregpipe,param_grid,cv=5,return_train_score=True)
logreg_cv.fit(X_under_train,y_under_train)
print(logreg_cv.best_params_)

bestlogreg = logreg_cv.best_estimator_
bestlogreg.fit(X_under_train,y_under_train)
bestlogreg.coef_ = bestlogreg.named_steps['logreg'].coef_
bestlogreg.score(X_under_train,y_under_train)

{'logreg__C': 10.01}


0.9418604651162791

# CROSS VALIDATION ON TEST & TRAIN DATA

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn import cross_validation

predicted = cross_validation.cross_val_predict(LogisticRegression(),X_under_train,y_under_train, cv=10)
print (metrics.accuracy_score(y_under_train, predicted))

0.9418604651162791


In [26]:
predicted1 = cross_validation.cross_val_predict(LogisticRegression(),X_under_test, y_under_test, cv=10)

print (metrics.classification_report(y_under_test, predicted1))
print (metrics.accuracy_score(y_under_test, predicted1))

             precision    recall  f1-score   support

          0       0.91      0.99      0.95       149
          1       0.99      0.90      0.94       147

avg / total       0.95      0.94      0.94       296

0.9425675675675675
